USE [CHECKMATE]
GO

/****** Object:  Table [dbo].[CERTIFICATE_STATUS_ISSUE]    Script Date: 9/5/2022 1:57:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CERTIFICATE_STATUS_ISSUE](
	[GUID] [uniqueidentifier] NOT NULL,
	[PUNCHLIST_STATUS_GUID] [uniqueidentifier] NOT NULL,
	[SEQUENCE_NUMBER] [numeric](10, 0) NOT NULL,
	[COMMENTS] [nvarchar](500) NOT NULL,
	[COMMENTS_READ] [bit] NOT NULL,
	[REJECTION] [bit] NOT NULL,
	[CREATED] [datetime] NOT NULL,
	[CREATEDBY] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_CERTIFICATE_STATUS_ISSUE] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


