USE [CHECKMATE]
GO

/****** Object:  Table [dbo].[CERTIFICATE_DATA]    Script Date: 10/5/2022 4:35:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CERTIFICATE_DATA](
	[GUID] [uniqueidentifier] NOT NULL,
	[CERTIFICATEGUID] [uniqueidentifier] NOT NULL,
	[DATA_TYPE] [nvarchar](50) NOT NULL,
	[DATA1] [nvarchar](500) NULL,
	[DATA2] [nvarchar](500) NULL,
	[DATA3] [nvarchar](500) NULL,
	[CREATED] [datetime] NOT NULL,
	[CREATEDBY] [uniqueidentifier] NOT NULL,
	[UPDATED] [datetime] NULL,
	[UPDATEDBY] [uniqueidentifier] NULL,
	[DELETED] [datetime] NULL,
	[DELETEDBY] [uniqueidentifier] NULL,
 CONSTRAINT [PK_CERTIFICATE_DATA] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CERTIFICATE_DATA]  WITH CHECK ADD  CONSTRAINT [FK_CERTIFICATE_DATA_CERTIFICATE_MAIN] FOREIGN KEY([CERTIFICATEGUID])
REFERENCES [dbo].[CERTIFICATE_MAIN] ([GUID])
GO

ALTER TABLE [dbo].[CERTIFICATE_DATA] CHECK CONSTRAINT [FK_CERTIFICATE_DATA_CERTIFICATE_MAIN]
GO


