USE [CHECKMATE]
GO

/****** Object:  Table [dbo].[PUNCHLIST_MAIN_PICTURE]    Script Date: 5/30/2022 6:23:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PUNCHLIST_MAIN_PICTURE](
	[GUID] [uniqueidentifier] NOT NULL,
	[PUNCHLIST_MAIN_GUID] [uniqueidentifier] NOT NULL,
	[PICTURE] [varbinary](max) NOT NULL,
	[CREATED] [datetime] NOT NULL,
	[CREATEDBY] [uniqueidentifier] NOT NULL,
	[UPDATED] [datetime] NULL,
	[UPDATEDBY] [uniqueidentifier] NULL,
	[DELETED] [datetime] NULL,
	[DELETEDBY] [uniqueidentifier] NULL,
 CONSTRAINT [PK_PUNCHLIST_MAIN_PICTURE] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


