USE [CHECKMATE]
GO

ALTER TABLE [dbo].[ITR_STATUS_ISSUE]  WITH CHECK ADD  CONSTRAINT [FK_ITRSTATUSISSUE_ITRSTATUS] FOREIGN KEY([ITR_STATUS_GUID])
REFERENCES [dbo].[ITR_STATUS] ([GUID])
GO

ALTER TABLE [dbo].[ITR_STATUS_ISSUE] CHECK CONSTRAINT [FK_ITRSTATUSISSUE_ITRSTATUS]
GO


