USE [CHECKMATE]
GO

ALTER TABLE [dbo].[PREFILL_REGISTER]  WITH CHECK ADD  CONSTRAINT [FK_PREFILL_TAG] FOREIGN KEY([TAG_GUID])
REFERENCES [dbo].[TAG] ([GUID])
GO

ALTER TABLE [dbo].[PREFILL_REGISTER] CHECK CONSTRAINT [FK_PREFILL_TAG]
GO


