USE [CHECKMATE]
GO

ALTER TABLE [dbo].[WORKFLOW_MAIN] DROP CONSTRAINT [FK_WORKFLOW_PROJECT]
GO

ALTER TABLE [dbo].[WORKFLOW_MAIN]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_PROJECT] FOREIGN KEY([PROJECTGUID])
REFERENCES [dbo].[PROJECT] ([GUID])
GO

ALTER TABLE [dbo].[WORKFLOW_MAIN] CHECK CONSTRAINT [FK_WORKFLOW_PROJECT]
GO


