//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckmateDX.SyncWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SyncWebService.CheckmateSyncSoap")]
    public interface CheckmateSyncSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        int Subtract(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        int Multiply(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        int Division(int x, int y);
        
        // CODEGEN: Generating message contract since element name strUser from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDatatable", ReplyAction="*")]
        CheckmateDX.SyncWebService.GetDatatableResponse GetDatatable(CheckmateDX.SyncWebService.GetDatatableRequest request);
        
        // CODEGEN: Generating message contract since element name strITR from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncITRData", ReplyAction="*")]
        CheckmateDX.SyncWebService.SyncITRDataResponse SyncITRData(CheckmateDX.SyncWebService.SyncITRDataRequest request);
        
        // CODEGEN: Generating message contract since element name hwid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sync_CheckApproval", ReplyAction="*")]
        CheckmateDX.SyncWebService.Sync_CheckApprovalResponse Sync_CheckApproval(CheckmateDX.SyncWebService.Sync_CheckApprovalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatatableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatatable", Namespace="http://tempuri.org/", Order=0)]
        public CheckmateDX.SyncWebService.GetDatatableRequestBody Body;
        
        public GetDatatableRequest() {
        }
        
        public GetDatatableRequest(CheckmateDX.SyncWebService.GetDatatableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDatatableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUser;
        
        public GetDatatableRequestBody() {
        }
        
        public GetDatatableRequestBody(string strUser) {
            this.strUser = strUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatatableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatatableResponse", Namespace="http://tempuri.org/", Order=0)]
        public CheckmateDX.SyncWebService.GetDatatableResponseBody Body;
        
        public GetDatatableResponse() {
        }
        
        public GetDatatableResponse(CheckmateDX.SyncWebService.GetDatatableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDatatableResponseBody {
        
        public GetDatatableResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SyncITRDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SyncITRData", Namespace="http://tempuri.org/", Order=0)]
        public CheckmateDX.SyncWebService.SyncITRDataRequestBody Body;
        
        public SyncITRDataRequest() {
        }
        
        public SyncITRDataRequest(CheckmateDX.SyncWebService.SyncITRDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncITRDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strITR;
        
        public SyncITRDataRequestBody() {
        }
        
        public SyncITRDataRequestBody(string strITR) {
            this.strITR = strITR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SyncITRDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SyncITRDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public CheckmateDX.SyncWebService.SyncITRDataResponseBody Body;
        
        public SyncITRDataResponse() {
        }
        
        public SyncITRDataResponse(CheckmateDX.SyncWebService.SyncITRDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SyncITRDataResponseBody {
        
        public SyncITRDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Sync_CheckApprovalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sync_CheckApproval", Namespace="http://tempuri.org/", Order=0)]
        public CheckmateDX.SyncWebService.Sync_CheckApprovalRequestBody Body;
        
        public Sync_CheckApprovalRequest() {
        }
        
        public Sync_CheckApprovalRequest(CheckmateDX.SyncWebService.Sync_CheckApprovalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Sync_CheckApprovalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hwid;
        
        public Sync_CheckApprovalRequestBody() {
        }
        
        public Sync_CheckApprovalRequestBody(string hwid) {
            this.hwid = hwid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Sync_CheckApprovalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sync_CheckApprovalResponse", Namespace="http://tempuri.org/", Order=0)]
        public CheckmateDX.SyncWebService.Sync_CheckApprovalResponseBody Body;
        
        public Sync_CheckApprovalResponse() {
        }
        
        public Sync_CheckApprovalResponse(CheckmateDX.SyncWebService.Sync_CheckApprovalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Sync_CheckApprovalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid Sync_CheckApprovalResult;
        
        public Sync_CheckApprovalResponseBody() {
        }
        
        public Sync_CheckApprovalResponseBody(System.Guid Sync_CheckApprovalResult) {
            this.Sync_CheckApprovalResult = Sync_CheckApprovalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckmateSyncSoapChannel : CheckmateDX.SyncWebService.CheckmateSyncSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckmateSyncSoapClient : System.ServiceModel.ClientBase<CheckmateDX.SyncWebService.CheckmateSyncSoap>, CheckmateDX.SyncWebService.CheckmateSyncSoap {
        
        public CheckmateSyncSoapClient() {
        }
        
        public CheckmateSyncSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckmateSyncSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckmateSyncSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckmateSyncSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public int Subtract(int x, int y) {
            return base.Channel.Subtract(x, y);
        }
        
        public int Multiply(int x, int y) {
            return base.Channel.Multiply(x, y);
        }
        
        public int Division(int x, int y) {
            return base.Channel.Division(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckmateDX.SyncWebService.GetDatatableResponse CheckmateDX.SyncWebService.CheckmateSyncSoap.GetDatatable(CheckmateDX.SyncWebService.GetDatatableRequest request) {
            return base.Channel.GetDatatable(request);
        }
        
        public void GetDatatable(string strUser) {
            CheckmateDX.SyncWebService.GetDatatableRequest inValue = new CheckmateDX.SyncWebService.GetDatatableRequest();
            inValue.Body = new CheckmateDX.SyncWebService.GetDatatableRequestBody();
            inValue.Body.strUser = strUser;
            CheckmateDX.SyncWebService.GetDatatableResponse retVal = ((CheckmateDX.SyncWebService.CheckmateSyncSoap)(this)).GetDatatable(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckmateDX.SyncWebService.SyncITRDataResponse CheckmateDX.SyncWebService.CheckmateSyncSoap.SyncITRData(CheckmateDX.SyncWebService.SyncITRDataRequest request) {
            return base.Channel.SyncITRData(request);
        }
        
        public void SyncITRData(string strITR) {
            CheckmateDX.SyncWebService.SyncITRDataRequest inValue = new CheckmateDX.SyncWebService.SyncITRDataRequest();
            inValue.Body = new CheckmateDX.SyncWebService.SyncITRDataRequestBody();
            inValue.Body.strITR = strITR;
            CheckmateDX.SyncWebService.SyncITRDataResponse retVal = ((CheckmateDX.SyncWebService.CheckmateSyncSoap)(this)).SyncITRData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckmateDX.SyncWebService.Sync_CheckApprovalResponse CheckmateDX.SyncWebService.CheckmateSyncSoap.Sync_CheckApproval(CheckmateDX.SyncWebService.Sync_CheckApprovalRequest request) {
            return base.Channel.Sync_CheckApproval(request);
        }
        
        public System.Guid Sync_CheckApproval(string hwid) {
            CheckmateDX.SyncWebService.Sync_CheckApprovalRequest inValue = new CheckmateDX.SyncWebService.Sync_CheckApprovalRequest();
            inValue.Body = new CheckmateDX.SyncWebService.Sync_CheckApprovalRequestBody();
            inValue.Body.hwid = hwid;
            CheckmateDX.SyncWebService.Sync_CheckApprovalResponse retVal = ((CheckmateDX.SyncWebService.CheckmateSyncSoap)(this)).Sync_CheckApproval(inValue);
            return retVal.Body.Sync_CheckApprovalResult;
        }
    }
}
