USE [CHECKMATE]
GO

ALTER TABLE [dbo].[ITR_MAIN]  WITH CHECK ADD  CONSTRAINT [FK_ITR_WBS] FOREIGN KEY([WBS_GUID])
REFERENCES [dbo].[WBS] ([GUID])
GO

ALTER TABLE [dbo].[ITR_MAIN] CHECK CONSTRAINT [FK_ITR_WBS]
GO

ALTER TABLE [dbo].[ITR_MAIN]  WITH CHECK ADD  CONSTRAINT [FK_ITR_TEMPLATE] FOREIGN KEY([TEMPLATE_GUID])
REFERENCES [dbo].[TEMPLATE_MAIN] ([GUID])
GO

ALTER TABLE [dbo].[ITR_MAIN] CHECK CONSTRAINT [FK_ITR_TEMPLATE]
GO

ALTER TABLE [dbo].[ITR_MAIN]  WITH CHECK ADD  CONSTRAINT [FK_ITR_TAG] FOREIGN KEY([TAG_GUID])
REFERENCES [dbo].[TAG] ([GUID])
GO

ALTER TABLE [dbo].[ITR_MAIN] CHECK CONSTRAINT [FK_ITR_TAG]
GO
