USE [CHECKMATE]
GO

ALTER TABLE [dbo].[ITR_STATUS]  WITH CHECK ADD  CONSTRAINT [FK_ITRSTATUS_ITR] FOREIGN KEY([ITR_MAIN_GUID])
REFERENCES [dbo].[ITR_MAIN] ([GUID])
GO

ALTER TABLE [dbo].[ITR_STATUS] CHECK CONSTRAINT [FK_ITRSTATUS_ITR]
GO


