USE [CHECKMATE]
GO

ALTER TABLE [dbo].[PREFILL_REGISTER]  WITH CHECK ADD  CONSTRAINT [FK_PREFILL_WBS] FOREIGN KEY([WBS_GUID])
REFERENCES [dbo].[WBS] ([GUID])
GO

ALTER TABLE [dbo].[PREFILL_REGISTER] CHECK CONSTRAINT [FK_PREFILL_WBS]
GO


