WITH RECURSIVETBL AS 
(
	SELECT a.*
	FROM ROLE_MAIN a
	WHERE PARENTGUID = '3f108fdf-8de0-4cf6-9f19-ca28843bcaf2'
	UNION ALL
	SELECT a.*
	FROM ROLE_MAIN a JOIN RECURSIVETBL r ON a.PARENTGUID = r.GUID
)
SELECT RECURSIVETBL.*, USR.*
FROM RECURSIVETBL
INNER JOIN USER_MAIN USR ON USR.ROLE = RECURSIVETBL.GUID
