USE [CHECKMATE]
GO

ALTER TABLE [dbo].[SCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_PROJECT] FOREIGN KEY([PROJECTGUID])
REFERENCES [dbo].[PROJECT] ([GUID])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[SCHEDULE] CHECK CONSTRAINT [FK_SCHEDULE_PROJECT]
GO


