USE [CHECKMATE]
GO

ALTER TABLE [dbo].[TEMPLATE_REGISTER]  WITH CHECK ADD  CONSTRAINT [FK_REGISTER_TAG] FOREIGN KEY([TAG_GUID])
REFERENCES [dbo].[TAG] ([GUID])
GO

ALTER TABLE [dbo].[TEMPLATE_REGISTER] CHECK CONSTRAINT [FK_REGISTER_TAG]
GO

ALTER TABLE [dbo].[TEMPLATE_REGISTER]  WITH CHECK ADD  CONSTRAINT [FK_REGISTER_WBS] FOREIGN KEY([WBS_GUID])
REFERENCES [dbo].[WBS] ([GUID])
GO

ALTER TABLE [dbo].[TEMPLATE_REGISTER] CHECK CONSTRAINT [FK_REGISTER_WBS]
GO


