USE [CHECKMATE]
GO

ALTER TABLE [dbo].[USER_PROJECT]
ADD CONSTRAINT FK_USERIDPROJ FOREIGN KEY (USERGUID)
       REFERENCES USER_MAIN (GUID)
       ON DELETE CASCADE
       ON UPDATE CASCADE
;

GO

ALTER TABLE [dbo].[USER_PROJECT]
ADD CONSTRAINT FK_PROJECTID FOREIGN KEY (PROJECTGUID)
       REFERENCES PROJECT (GUID)
       ON DELETE CASCADE
       ON UPDATE CASCADE
;

GO
