USE [CHECKMATE]
GO

ALTER TABLE [dbo].[USER_ROLE]
ADD CONSTRAINT FK_USERIDROLE FOREIGN KEY (USERGUID)
       REFERENCES USER_MAIN (GUID)
       ON DELETE CASCADE
       ON UPDATE CASCADE
;

GO

ALTER TABLE [dbo].[USER_ROLE]
ADD CONSTRAINT FK_ROLEID FOREIGN KEY (ROLEGUID)
       REFERENCES ROLE_MAIN (GUID)
       ON DELETE CASCADE
       ON UPDATE CASCADE
;

GO
