USE [CHECKMATE]
GO

ALTER TABLE [dbo].[WBS]  WITH CHECK ADD  CONSTRAINT [FK_WBS_SCHEDULE] FOREIGN KEY([SCHEDULEGUID])
REFERENCES [dbo].[SCHEDULE] ([GUID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[WBS] CHECK CONSTRAINT [FK_WBS_SCHEDULE]
GO


